### ISSUE TITLE
Style transform needs tag name and instance/id in to scope correctly. 

### ISSUE THREAD

**Issue by ryanbethel** [enhance-dev/enhance-ssr#14]
The `styleTransforms` currently only pass the `attrs` and css string. In order to be able to do the scoping transforms shown in [https://github.com/enhance-dev/prototypes](https://github.com/enhance-dev/prototypes) they need the name of the tag and an instance ID. 

```css
:host {
  display: block;
}
```
Needs to be transformed into:
```css
tag-name {
  display: block;
}
```

The same is true for scoping to an individual instance where an ID is used in the templated HTML and a section of CSS should be scoped to that ID.
